spring:
  application:
    name: server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false
server:
  port: 8761

#eureka:
#  client:
#    service-url:
#      defaultZone: http://peer1:8761/eureka/
#  instance:
#    prefer-ip-address: true
#server:
#  port: 8762
#spring:
#  profiles: peer2